config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :storerooms do
    member do
       get :toggle_status
    end
  end
  root "storerooms#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/storeroom.rb
class Storeroom < ApplicationRecord
	has_one_attached :image
	enum status: { public_store: 0, private_store: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/storerooms_controller.rb
class StoreroomsController  < ApplicationController
	before_action :set_storeroom ,only: [:edit,:update,:show,:destroy, :toggle_status]

	def index
		@storerooms=Storeroom.all
	end
	def new
		@storeroom=Storeroom.new
	end
	def create
		@storeroom=Storeroom.new(storeroom_params)
		if @storeroom.save
			redirect_to storerooms_path
		else
			render :new
		end
	end
	def show

	end
	def edit
	end
	def toggle_status
		if @storeroom.public_store?
			@storeroom.private_store!
		else
			 # @storeroom.private_store?
			@storeroom.public_store!
		end

		redirect_to storerooms_path
	end
	def update
		if @storeroom.update(storeroom_params)
			redirect_to storerooms_path
		else
			render :edit
		end
	end
	def destroy
		if @storeroom.destroy
			redirect_to storerooms_path
		end
	end
	private
	def storeroom_params
		params.require(:storeroom).permit(:username, :email ,:image)
	end
	def set_storeroom
		@storeroom = Storeroom.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mystoreroom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/storerooms/_form.html.erb
<div class="row mt-5">
  <div class="mx-auto col-10 col-md-8 col-lg-6">
  	<%= form_with(model: storeroom) do |form|%>
      <h1>StoreRoom</h1>
      	<div class="bg-dark col-lg-8 form-control">
      		<div class="row col-lg-12 bg-dark">
				<%=form.label :username, class:"form-control mb-3 bg-dark text-white border-0" %>
				<%= form.text_field :username ,class:"form-control mb-2" %>
			</div>
		    <div class="row col-lg-12 bg-dark">
				<%=form.label :email, class:"form-control mb-3 bg-dark text-white border-0" %>
				<%= form.email_field :email ,class:"form-control text-color-white" %>
			</div>
			<div class="row col-lg-12 bg-dark mt-2">
				<%=form.label :Attachment, class:"form-control mb-3 bg-dark text-white border-0" %>
				<%= form.file_field :image ,class:"form-control text-color-white" %>
			</div>
			<br><br>

      	</div>
	
		<%= form.submit class:"btn btn-primary mt-5"%>
		<%= link_to "Back" , storerooms_path ,class:"btn btn-dark mt-5" %>
	<%end%>
  </div>
</div>

app/views/storerooms/edit.html.erb
<%= render "form", storeroom: @storeroom %>

app/views/storerooms/index.html.erb
<div class="d-flex flex-wrap flex-row mx-5 px-5">
	<% @storerooms.each do |data| %>
		<div class="card mt-5 mx-3" style="width: 23rem; ">
			  <div class="card-body">
			    <h5 class="card-title"><%= data.username%></h5>
				    <div class="card-subtitle mb-2 text-muted">
				    	<p><%= data.email%></p>
				    	<%= image_tag data.image ,class:"card-img-top mb-2" %>
				    	<%= link_to "show" , data ,class:"btn btn-secondary"%>
				    	<%= link_to "edit" , edit_storeroom_path(data) ,class:"btn btn-dark"%>
				    </div>
				    	<%= button_to "Delete" , data ,class:"btn btn-danger" , method: :delete, data: {confirm: 'Are you sure?'}%>
				    	<%= link_to data.status , toggle_status_storeroom_path(data) %>

			  </div>
			</div>
		<div class="px-3">
		</div>
	<% end %>
	</div>
<%= link_to "new item", new_storeroom_path ,class:"btn btn-primary mx-5 mt-5"%>

app/views/storerooms/new.html.erb
<%= render "form", storeroom: @storeroom %>

app/views/storerooms/show.html.erb
<div class="card mx-auto col-10 col-md-8 col-lg-6 mt-5" style="width: 18rem;">
  <!-- <img src="..." class="card-img-top" alt="..."> -->
  <%= image_tag @storeroom.image ,class:"card-img-top" %>
  <div class="card-body">
    <h5 class="card-title"><%= @storeroom.username %></h5>
    <p class="card-text"><%= @storeroom.email %></p>
    <%= link_to "Destroy this storeroom", @storeroom,class:"btn btn-danger", method: :delete ,data: {confirm: "Are You Sure?"}%>
    <%= link_to "Back" , storerooms_path ,class:"btn btn-primary" %>
  </div>
</div>